---

- name: Install oracle mysql
  include: mysql.yml
  when: mysql_version == 'mysql'

- name: Install mariadb
  include: mariadb.yml
  when: mysql_version == 'mariadb'

- name: Start mysql server
  systemd:
    name: mysql
    state: started

- name: get .my.cnf state
  stat:
    path: /root/.my.cnf
  register: _my_cnf

- name: Update MySQL root password
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
  with_items:
  - "{{ ansible_hostname }}"
  - "127.0.0.1"
  - "::1"
  - "localhost"
  when: _my_cnf.stat.exists == False

- name: Copy .my.cnf file into the root home folder
  template:
    src: root.my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    mode: 0600
  when: _my_cnf.stat.exists == False

- name: Ensure anonymous users are not in the database
  become: true
  become_user: root
  mysql_user:
    name: ''
    host: "{{ item }}"
    state: absent
  with_items:
  - "{{ ansible_hostname }}"
  - localhost

- name: remove test database
  mysql_db:
    name: test
    state: absent

...
